// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'datum.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Datum _$DatumFromJson(Map<String, dynamic> json) => Datum(
      code: (json['Code'] as num?)?.toInt(),
      fileNo: json['FileNo'] as String?,
      barcode: (json['Barcode'] as num?)?.toInt(),
      typeCode: (json['TypeCode'] as num?)?.toInt(),
      name: json['Name'] as String?,
      noOfDays: (json['NoOfDays'] as num?)?.toInt(),
      maximumSeat: (json['MaximumSeat'] as num?)?.toInt(),
      minimumAdvanceAmt: (json['MinimumAdvanceAmt'] as num?)?.toInt(),
      isPackage: (json['isPackage'] as num?)?.toInt(),
      vehicleCode: (json['VehicleCode'] as num?)?.toInt(),
      startDate: json['StartDate'] as String?,
      endDate: json['EndDate'] as String?,
      details: json['Details'] as String?,
      termsAndCondetion: json['TermsAndCondetion'] as String?,
      cancelPolicy: json['CancelPolicy'] as String?,
      boardingPoint: json['BoardingPoint'] as String?,
      boardingTime: json['BoardingTime'] as String?,
      amount: (json['Amount'] as num?)?.toInt(),
      dot: json['DOT'] as String?,
      postedBy: (json['PostedBy'] as num?)?.toInt(),
      isActive: (json['IsActive'] as num?)?.toInt(),
      guideName: json['GuideName'] as String?,
      guideContactNo: json['GuideContactNo'] as String?,
      layout: json['Layout'] as String?,
      contactNo: json['ContactNo'],
      bookingEndDate: json['BookingEndDate'] as String?,
      branchCode: (json['BranchCode'] as num?)?.toInt(),
      tourType: json['TourType'],
      availableSeat: (json['AvailableSeat'] as num?)?.toInt(),
      vehicleNo: json['VehicleNo'],
      vehicleDetails: json['VehicleDetails'],
      driverName: json['DriverName'],
      driverPhoneNo: json['DriverPhoneNo'],
      tourTypeName: json['TourTypeName'],
      pnr: (json['PNR'] as num?)?.toInt(),
    );

Map<String, dynamic> _$DatumToJson(Datum instance) => <String, dynamic>{
      'Code': instance.code,
      'FileNo': instance.fileNo,
      'Barcode': instance.barcode,
      'TypeCode': instance.typeCode,
      'Name': instance.name,
      'NoOfDays': instance.noOfDays,
      'MaximumSeat': instance.maximumSeat,
      'MinimumAdvanceAmt': instance.minimumAdvanceAmt,
      'isPackage': instance.isPackage,
      'VehicleCode': instance.vehicleCode,
      'StartDate': instance.startDate,
      'EndDate': instance.endDate,
      'Details': instance.details,
      'TermsAndCondetion': instance.termsAndCondetion,
      'CancelPolicy': instance.cancelPolicy,
      'BoardingPoint': instance.boardingPoint,
      'BoardingTime': instance.boardingTime,
      'Amount': instance.amount,
      'DOT': instance.dot,
      'PostedBy': instance.postedBy,
      'IsActive': instance.isActive,
      'GuideName': instance.guideName,
      'GuideContactNo': instance.guideContactNo,
      'Layout': instance.layout,
      'ContactNo': instance.contactNo,
      'BookingEndDate': instance.bookingEndDate,
      'BranchCode': instance.branchCode,
      'TourType': instance.tourType,
      'AvailableSeat': instance.availableSeat,
      'VehicleNo': instance.vehicleNo,
      'VehicleDetails': instance.vehicleDetails,
      'DriverName': instance.driverName,
      'DriverPhoneNo': instance.driverPhoneNo,
      'TourTypeName': instance.tourTypeName,
      'PNR': instance.pnr,
    };
